[package]
name = "avocado"
version = "0.1.0"
edition = "2021"
description = "2D game framework for personal uses"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AvantTeam/avocado"

[workspace]
resolver = "2"
members = [
    "avocado_dyn",
    "avocado_lib"
]

[features]
default = [
    "log",
    "core",
    "asset", "asset_folder",
    "winit", "winit_2d",
]

dynamic = ["dep:avocado_dyn"]

log = ["avocado_lib/log"]
core = ["avocado_lib/core"]
asset = ["avocado_lib/asset"]
asset_folder = ["avocado_lib/asset_folder"]
asset_embedded = ["avocado_lib/asset_embedded"]
winit = ["avocado_lib/winit"]
winit_2d = ["avocado_lib/winit_2d"]

[dependencies]
avocado_dyn = { path = "avocado_dyn", version = "0.1.0", optional = true }
avocado_lib = { path = "avocado_lib", version = "0.1.0", default-features = false }

[build-dependencies]
cargo-emit = "0.2"

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"
required-features = ["log"]

[[example]]
name = "asset_basic"
path = "examples/asset/asset_basic.rs"
required-features = ["log", "core", "asset", "asset_folder"]

[[example]]
name = "asset_graph"
path = "examples/asset/asset_graph.rs"
required-features = ["log", "core", "asset", "asset_folder"]

[[example]]
name = "fixed_timestep"
path = "examples/core/fixed_timestep.rs"
required-features = ["log", "core"]

[[example]]
name = "hello_graphics"
path = "examples/winit/hello_graphics.rs"
required-features = ["log", "core", "winit"]
